- setup.sh
- utils.js
Closes https://github.com/w3c/spec-prod/issues/15
> fix: use file commands for set-env and add-path

- package.json
- src/build.js
- src/utils.js
Address https://github.com/w3c/respec/issues/3292
> fix(build): use static http server with ReSpec

- src/prepare.js
Overcoming a limitation from https://github.com/w3c/spec-prod/pull/27
> feat(prepare/build/w3c): figure out ReSpec shortName from input file

- src/validate-links.js
Should add ability to skip certain URLs and allow certain errors in `href-checker` first.
> chore(validate/links): disable until bugs are fixed

- src/prepare-build.ts
Closes https://github.com/w3c/spec-prod/issues/30
> feat(prepare/build): figure out shortname for bikeshed docs

- src/prepare-build.ts
Fixes https://github.com/w3c/spec-prod/issues/50
> fix(prepare/build): ensure destination has .html extension

- src/deploy-w3c-echidna.ts
Fixed https://github.com/w3c/spec-prod/issues/50
Regression from https://github.com/w3c/spec-prod/pull/45
> fix(deploy/w3c): rename/copy correct files

- .github/workflows/docs.yml
- docs/index.html
- docs/options.md
Supersedes https://github.com/w3c/spec-prod/pull/62
> docs: add single page doc using ReSpec

- docs/index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/pull/73.html" title="Last updated on May 31, 2021, 7:27 PM UTC (9af95f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/73/8100103...9af95f4.html" title="Last updated on May 31, 2021, 7:27 PM UTC (9af95f4)">Diff</a>
> docs(index.html): improve postProcess.fixLinks

- src/deploy-w3c-echidna.ts
- src/prepare-deploy.ts
> feat(deploy/w3c): add Echidna annotation parameter

- src/validate-webidl.ts
Fixes https://github.com/w3c/spec-prod/issues/105
> fix(validate/webidl): remove stray .cache dir

- src/utils.ts
Closes https://github.com/w3c/spec-prod/issues/111
> feat(utils/install): print installed version

- .github/workflows/pr.yml
- action.yml
- package.json
Part of https://github.com/w3c/spec-prod/issues/99
> chore(action): use node 16

- action.yml
- src/validate-links.ts
Part of https://github.com/w3c/spec-prod/issues/5
> chore: Skip VALIDATE_LINKS at step level

- src/prepare-build.ts
Fixes https://github.com/w3c/spec-prod/issues/128
> fix(prepare/build): enable Bikeshed "Prepare for TR" for TR specs

- action.yml
- Fixes #117
- Fixes #130
- Fixes #136
- Fixes #137
Workaround for https://github.com/actions/runner/issues/1722
Tested in https://github.com/sidvishnoi/manifest/pull/2
> fix: avoid showing "template is not valid" error

- src/prepare-deploy.ts
Part of https://github.com/w3c/spec-prod/issues/6
> feat(deploy): allow deploy with `workflow_dispatch` events

- .github/workflows/docs.yml
- .github/workflows/pr.yml
- README.md
- docs/README.md
- docs/examples.md
chore(ci): use `actions/checkout@v4`
Closes https://github.com/w3c/spec-prod/issues/160
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/pull/162.html" title="Last updated on Sep 12, 2023, 8:20 AM UTC (4febf17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/162/6377180...4febf17.html" title="Last updated on Sep 12, 2023, 8:20 AM UTC (4febf17)">Diff</a>
> docs: recommend `actions/checkout@v4`

- .github/workflows/docs.yml
- .github/workflows/pr.yml
- action.yml
- src/constants.ts
Closes https://github.com/w3c/spec-prod/issues/170
> fix: rename puppeteer env var flag to `PUPPETEER_SKIP_DOWNLOAD`

- .github/workflows/pr.yml
- action.yml
- package.json
- pnpm-lock.yaml
- src/prepare-build.ts
- Fixes https://github.com/w3c/spec-prod/issues/171
- Closes https://github.com/w3c/spec-prod/pull/169
> chore(deps): update dependencies
