w3c/spec-prod

action.yml
deploy-w3c-echidna.js
docs/examples.md
docs/options.md
prepare.js

BREAKING CHANGE: `W3C_MANIFEST_URL` will no longer be supported.
- ~add option to configure `specStatus` and `shortName`~ This should be done at spec config level*.
Closes https://github.com/w3c/spec-prod/issues/12
Closes https://github.com/w3c/spec-prod/issues/21
\* With ReSpec, something like following should be possible:
```js
var respecConfig = {
specStatus: "WD",
}
if (isGitHubPages()) {
respecConfig.specStatus = "ED";
}
```

feat(deploy/w3c): upload tar instead of using manifest

---

action.yml
docs/options.md
src/build.js
src/prepare.js

Allows configuring on what kinds of errors/warnings build should fail. By default, fails on fatal errors.
Closes https://github.com/w3c/spec-prod/issues/19
Closes https://github.com/w3c/spec-prod/issues/20

feat(build): add BUILD_FAIL_ON config option

---

action.yml
docs/examples.md
docs/options.md
src/build.js
src/prepare.js
test/build.test.js
test/deploy-gh-pages.test.js
test/prepare.test.js
test/validate-links.test.js
test/validate-markup.test.js

- Added `W3C_BUILD_OVERRIDE` and `GH_PAGES_BUILD_OVERRIDE` inputs.
- The config updated with `W3C_BUILD_OVERRIDE` will be used for w3c-deploy and validations.
- The config updated with `GH_PAGES_BUILD_OVERRIDE` will be used only in gh-pages-deploy deploy.
- If neither is provided, a single build using the default config will be used for validations, w3c-deploy and gh-pages-deploy.

feat: override build config for W3C and gh-pages builds

---

package.json
src/prepare.js

Using previously published document, finds following information to use with W3C builds:
- ReSpec: `previousMaturity` and `previousPublishDate`,
- Bikeshed: `previous version`
`shortName` (ReSpec) / `shortname` (Bikeshed) must be set in `W3C_BUILD_OVERRIDE`.

feat(prepare): get W3C build config from previously published TR doc

---

src/build.js

Fixes https://github.com/w3c/spec-prod/issues/20
~@dontcallmedom can you validate before release by using `w3c/spec-prod@bikeshed-die-on-is-global-flag` instead of `w3c/spec-prod@v2`?~ nvm. I tested locally.

fix(build/bikeshed): use --die-on as a global option

---

action.yml
docs/options.md

Even after the bugs with link checking get fixed, it’s better to make link checking an opt-in rather than an opt-out. So this change sets VALIDATE_LINKS to false by default.
---
In my long experience with running drafts through pubrules, there are very many times when I’ve needed to ask the W3C webmaster to OK a publication despite errors from the link checker.
The reasons include the fact that the link checker — and link-checking is general — is known to sometimes (or often) produce false positives. And other reasons. It’s complicated.
And so given that, I don’t think it’s prudent to impose link checking on spec editors by default, and force them all to opt out — because I can tell you that if we keep the default at true, I think what we’re going to end up seeing is that very many (or …

Make VALIDATE_LINKS false by default

---

action.yml
package.json
src/build.ts
src/utils.ts
yarn.lock

remove `local-assets` dependency by writing application-specific logic
...which also improves performance by not running subresources twice
Closes https://github.com/w3c/spec-prod/issues/32
Currently only allows external content from https://user-images.githubusercontent.com, more URLs can be added as needed.

feat(build): download remote assets before deploy

---

docs/examples.md

This adjusts the documentation for a multi-documents repository to clarify how to pass Echidna tokens per document (see #55), and to highlight the possible need to serialize jobs (at least until #58 gets addressed).

docs(examples/multi-spec): how to set secrets, avoid push conflicts

---

src/prepare-build.ts

See #92.
I'm not sure how to test this. Issuing `npm run build` on my machine with the current contents of the repository reports 12 TypeScript errors. Is there something special I should be doing to set things up?

fix(prepare/build): support deeply nested SOURCE paths

---

package.json
src/build.ts
src/utils.ts
yarn.lock

- Closes https://github.com/w3c/spec-prod/issues/131
- Closes https://github.com/w3c/spec-prod/issues/39
In the built file, finds local `a[href]`, copies them and their subresources.
Tested on [MiniApp Standardization White Paper](https://w3c.github.io/miniapp/white-paper/) and [Media Source](https://w3c.github.io/media-source/) (had to update the github.io URL to relative one).
Limitations:
- Files must be within same directory as source file (will fix this as a followup; [clreq example](https://github.com/w3c/spec-prod/issues/39#issuecomment-850957812) doesn't work as of now).
- Files must be referenced as a relative URL.

feat(build): copy linked files and their subresources

---

src/build.ts

Fixes https://github.com/w3c/spec-prod/issues/134
Earlier, we were adding `nextPage` to root pages even when we failed to fetch it (unnoticed double call to `pages.add`). Now, we check before trying to get its subresources. Added a warning when we skip a page too.

fix(build/copy-assets): prevent crash if can't fetch page

---

src/deploy-gh-pages.ts

It's rather annoying behavior to notify someone about something they don't have to take any action on.

fix(deploy/gh-pages): don't notify users with mention in commit msg

---

action.yml

So we can pick up their update to node 16 and avoid warnings about node 12 being deprecated.

chore(deps): allow minor updates to `pnpm/action-setup`

---

action.yml
src/validate-pubrules.ts
test/validate-pubrules.test.ts

API keys are no longer needed for pubrules

fix(validate/pubrules): API key is no longer required

---

action.yml

Closes https://github.com/w3c/spec-prod/issues/164

fix(action.yml): use `.nvmrc`, `package.json` in action repo

---

src/build.ts
src/prepare-build.ts
src/prepare.ts

Useful if https://github.com/w3c/respec/pull/4561 gets merged

feat(build): pass git commit sha for ReSpec based specs

---

src/validate-webidl.ts

- Fixes https://github.com/w3c/spec-prod/issues/176
- Fixes https://github.com/w3c/spec-prod/issues/175

fix(validate/webidl): set puppeteer exec path for reffy

---

action.yml
docs/examples.md
docs/options.md

In [v2.11.0](https://github.com/w3c/spec-prod/releases/tag/v2.11.0), `actions/upload-artifact` [was updated to v4](https://github.com/w3c/spec-prod/pull/173) which started to cause issues in the WebExtensions Community Group repository. In particular, v4 requires each invocation to have a unique artifact name (this was a [breaking change](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact)) and that does not hold true when using spec-prod since there is no way to configure the name.
[Configuration](https://github.com/w3c/webextensions/blob/5ec00959f2f0710d2d95a71adbe891786a2c6cf7/.github/workflows/deploy.yml#L46) / [Example failure](https://github.com/w3c/webextensions/actions/runs/8703930854/job/23871146610)
To resolve this, …

fix: don't break with multiple specs, add `ARTIFACT_NAME` option

---

action.yml
docs/examples.md
docs/options.md
src/build.ts
src/prepare-build.ts
src/prepare.ts

Automatically generate artifact name based on source. Respect `ARTIFACT_NAME` set in inputs, as added in https://github.com/w3c/spec-prod/pull/180.
So that https://github.com/w3c/spec-prod/pull/173 will no longer be a breaking as mentioned [`v2.11.2`](https://github.com/w3c/spec-prod/releases/tag/v2.11.2).
The artifact name may change from `spec-prod-result` even with single spec, though some effort was made to keep it stable (i.e. if source is `index.html` or `index.bs`). The automatic name will still start with `spec-prod-result`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/pull/181.html" title="Last updated on Apr 17, 2024, 1:19 PM UTC (e412ddb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/181/5cf6473...e412ddb.html" title="Last updated …

fix: don't require `ARTIFACT_NAME` with multiple specs

---

src/deploy-w3c-echidna.ts

Fixes https://github.com/w3c/spec-prod/issues/182

fix(deploy/w3c): don't crash if file is already named `Overview.html`

---

src/setup.ts

To avoid 'error: externally-managed-environment' in ubuntu-24.04. This is now the method recommended by https://speced.github.io/bikeshed/#install-normal.
Fixes #189. It's possible that we can also now remove the `cwd` and `env` parameters, but I haven't done the testing necessary to be confident of that.

fix(setup): use pipx to install Bikeshed

---

README.md
docs/README.md
docs/examples.md

Ubuntu 20 shipped with Python 3.8, which limits Bikeshed to a version from Nov 2023.
***
<a href="https://pr-preview.s3.amazonaws.com/tabatkins/spec-prod/pull/193.html" title="Last updated on Nov 22, 2024, 8:51 AM UTC (7051abc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/193/ebf41d9...tabatkins:7051abc.html" title="Last updated on Nov 22, 2024, 8:51 AM UTC (7051abc)">Diff</a>

docs: recommend running on ubuntu-latest

---

.github/workflows/pr.yml

[GitHub will no longer support the Ubuntu 20.04 runner image starting from April 1, 2025](https://github.com/actions/runner-images/issues/11101). That PR updates the actions to use ubuntu-latest instead

chore(ci/pr): replace ubuntu-20.04 with ubuntu-latest

---

src/prepare-validate.ts
src/prepare.ts

The use of W3C_API_KEY was removed in #161.
Fixes #204.

fix: remove the W3C_API_KEY requirement for VALIDATE_PUBRULES

---

.github/workflows/docs.yml
.github/workflows/pr.yml
README.md
docs/README.md
docs/examples.md

Update the documentation to use [actions/checkout@v5](https://github.com/actions/checkout#checkout-v5).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/pull/208.html" title="Last updated on Aug 28, 2025, 8:23 AM UTC (7d93bed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/spec-prod/208/5402361...7d93bed.html" title="Last updated on Aug 28, 2025, 8:23 AM UTC (7d93bed)">Diff</a>

chore: switch to actions/checkout@v5
